-- Insert designations data
INSERT INTO `designations` (`id`, `name`, `category`, `created`, `modified`) VALUES
(6, 'Physician', 1, NOW(), NOW()),
(7, 'Physiotherapist', 1, NOW(), NOW()),
(8, 'Nurse', 1, NOW(), NOW()),
(9, 'Pharmaceutical technologist', 1, NOW(), NOW()),
(10, 'Laboratory Technician', 1, NOW(), NOW()),
(11, 'Pharmacist', 1, NOW(), NOW()),
(12, 'Health Records and Information Officer', 1, NOW(), NOW()),
(13, 'Family Physician', 1, NOW(), NOW()),
(14, 'Dentist', 1, NOW(), NOW()),
(15, 'Laboratory technologist', 1, NOW(), NOW()),
(16, 'Nutritionist', 1, NOW(), NOW()),
(17, 'Biomedical engineer', 1, NOW(), NOW()),
(18, 'Surgeon', 1, NOW(), NOW()),
(19, 'Paediatrician', 1, NOW(), NOW()),
(20, 'Anaesthetist', 1, NOW(), NOW()),
(21, 'Clinical officer', 1, NOW(), NOW()),
(22, 'Psychiatrist', 1, NOW(), NOW()),
(23, 'Obstetrician/Gynaecologist', 1, NOW(), NOW()),
(24, 'Radiographer', 1, NOW(), NOW()),
(25, 'Medical officer', 1, NOW(), NOW()),
(26, 'Patient', 1, NOW(), NOW()),
(27, 'Relative/Friend/Guardian/Parent', 1, NOW(), NOW()),
(28, 'Other Health Care Professional', 1, NOW(), NOW()),
(31, 'Lawyer', 1, NOW(), NOW()),
(32, 'Research assistant', 1, NOW(), NOW()),
(33, 'Ophthalmologist', 1, NOW(), NOW()),
(34, '', 1, NOW(), NOW());

-- Insert counties data
INSERT INTO `counties` (`id`, `county_name`, `org_unit`, `created`, `modified`) VALUES
(1, 'Mombasa', NULL, NOW(), NOW()),
(2, 'Kwale', NULL, NOW(), NOW()),
(3, 'Kilifi', NULL, NOW(), NOW()),
(4, 'Tana River', NULL, NOW(), NOW()),
(5, 'Lamu', NULL, NOW(), NOW()),
(6, 'Taita Taveta', NULL, NOW(), NOW()),
(7, 'Garissa', NULL, NOW(), NOW()),
(8, 'Wajir', NULL, NOW(), NOW()),
(9, 'Mandera', NULL, NOW(), NOW()),
(10, 'Marsabit', NULL, NOW(), NOW()),
(11, 'Isiolo', NULL, NOW(), NOW()),
(12, 'Meru', NULL, NOW(), NOW()),
(13, 'Tharaka Nithi', NULL, NOW(), NOW()),
(14, 'Embu', NULL, NOW(), NOW()),
(15, 'Kitui', NULL, NOW(), NOW()),
(16, 'Machakos', NULL, NOW(), NOW()),
(17, 'Makueni', NULL, NOW(), NOW()),
(18, 'Nyandarua', NULL, NOW(), NOW()),
(19, 'Nyeri', NULL, NOW(), NOW()),
(20, 'Kirinyaga', NULL, NOW(), NOW()),
(21, 'Murang''a', NULL, NOW(), NOW()),
(22, 'Kiambu', NULL, NOW(), NOW()),
(23, 'Turkana', NULL, NOW(), NOW()),
(24, 'West Pokot', NULL, NOW(), NOW()),
(25, 'Samburu', NULL, NOW(), NOW()),
(26, 'Trans Nzoia', NULL, NOW(), NOW()),
(27, 'Uasin Gishu', NULL, NOW(), NOW()),
(28, 'Elgeyo/Marakwet', NULL, NOW(), NOW()),
(29, 'Nandi', NULL, NOW(), NOW()),
(30, 'Baringo', NULL, NOW(), NOW()),
(31, 'Laikipia', NULL, NOW(), NOW()),
(32, 'Nakuru', NULL, NOW(), NOW()),
(33, 'Narok', NULL, NOW(), NOW()),
(34, 'Kajiado', NULL, NOW(), NOW()),
(35, 'Kericho', NULL, NOW(), NOW()),
(36, 'Bomet', NULL, NOW(), NOW()),
(37, 'Kakamega', NULL, NOW(), NOW()),
(38, 'Vihiga', NULL, NOW(), NOW()),
(39, 'Bungoma', NULL, NOW(), NOW()),
(40, 'Busia', NULL, NOW(), NOW()),
(41, 'Siaya', NULL, NOW(), NOW()),
(42, 'Kisumu', NULL, NOW(), NOW()),
(43, 'Homa Bay', NULL, NOW(), NOW()),
(44, 'Migori', NULL, NOW(), NOW()),
(45, 'Kisii', NULL, NOW(), NOW()),
(46, 'Nyamira', NULL, NOW(), NOW()),
(47, 'Nairobi County', NULL, NOW(), NOW());